import {
  companyParamsSchema,
  companySchema,
  errorSchema,
  companysSchema,
  containerSchema,
  containersSchema,
  containerParamsSchema,
  uploadMediaContainerSchema,
  selectChatlineParamsSchema,
  chatlineSchema,
  endChatlineParamsSchema,
  chatlinesSchema,
  sendMessageParamsSchema,
  greetingSchema,
  greetingParamsSchema,
} from './schemas/';

export default {
  error: errorSchema,
  companyParams: companyParamsSchema,
  company: companySchema,
  companys: companysSchema,
  container: containerSchema,
  containers: containersSchema,
  containerParams: containerParamsSchema,
  uploadMediaContainerParams: uploadMediaContainerSchema,
  selectChatlineParams: selectChatlineParamsSchema,
  chatline: chatlineSchema,
  endChatlineParams: endChatlineParamsSchema,
  chatlines: chatlinesSchema,
  sendMessageParams: sendMessageParamsSchema,
  greeting: greetingSchema,
  greetingParams: greetingParamsSchema,
};
